"""Public API for the trend_estimation research library."""

from importlib.metadata import PackageNotFoundError, version

from trend_estimation.benchmarks import (
    BenchmarkResult,
    BenchmarkRunner,
    benchmark_metrics_table,
    default_benchmark_models,
    no_change_forecast,
    run_benchmark,
)
from trend_estimation.core import (
    GuerreroSpectralSolver,
    PurePenalizedSolver,
    PureSolverResult,
    PureTrendDerivatives,
    difference_coefficients,
    difference_matrix,
    effective_degrees_of_freedom,
    lambda_to_smoothness,
    mse_from_prediction_derivatives,
    penalized_solution,
    pure_penalized_solution,
    pure_trend_derivatives,
    roughness,
    smoothness_to_lambda,
)
from trend_estimation.datasets import (
    SyntheticTrendData,
    make_local_linear_ar1_series,
    make_local_linear_trend_series,
    make_noisy_trend_series,
    make_piecewise_trend_series,
    make_polynomial_trend_series,
    make_sinusoidal_trend_series,
    make_structural_break_series,
    make_two_regime_local_linear_series,
)
from trend_estimation.forecasting import (
    ForecastAffineOperator,
    ForecastLossDerivatives,
    ForecastResult,
    RollingForecastLossDerivatives,
    PreparedRollingPureForecastObjective,
    prepare_rolling_pure_forecast_objective,
    build_polynomial_from_tail,
    finite_difference_forecast_operator,
    forecast_trend,
    pure_forecast_loss_derivatives,
    rolling_pure_forecast_loss_derivatives,
)
from trend_estimation.metrics import (
    compare_error_tables,
    error_metrics_table,
    mae,
    mape,
    mse,
    rmse,
    roughness_d,
    smape,
)
from trend_estimation.models import (
    ExponentialSmoothingTrend,
    GuerreroTrend,
    HPTrend,
    IteratedDriftTrend,
    MovingAverageTrend,
    PolynomialTrendForecaster,
    PurePenalizedTrend,
    WhittakerTrend,
)
from trend_estimation.plotting import (
    plot_benchmark_forecasts,
    plot_benchmark_metrics,
    plot_forecasted_trend,
    plot_metrics_table,
    plot_smoothed_series,
    plot_train_val_test_split,
    plot_validation_curve,
    set_style,
)
from trend_estimation.selection import (
    ForecastOptimalCandidate,
    ForecastOptimalSelection,
    LambdaOptimizationResult,
    RecoveryLossDerivatives,
    RecoveryOptimalSelection,
    StationaryPoint,
    StationaryPointSearchResult,
    TimeWeightedValidationSelector,
    TrainValidationSelector,
    find_all_local_minima,
    find_stationary_points_log_lambda,
    golden_local,
    minimize_over_log_lambda,
    newton_stationary_log_lambda,
    pure_recovery_loss_derivatives,
    select_fixed_window_pure_smoothness,
    select_recovery_optimal_lambda,
)
from trend_estimation.validation import (
    RollingOriginSplit,
    TimeWeightedValidationLoss,
    make_time_weights,
    mse_loss,
    rolling_origin_splits,
    train_val_test_split,
    train_val_test_split_indices,
    weighted_mse,
)
from trend_estimation.validation.nested_forecast import (
    NestedForecastRecord,
    NestedRollingForecastResult,
    nested_rolling_pure_forecast,
)

try:
    __version__ = version("trend-estimation")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    # Models
    "PurePenalizedTrend",
    "GuerreroTrend",
    "IteratedDriftTrend",
    "HPTrend",
    "WhittakerTrend",
    "MovingAverageTrend",
    "ExponentialSmoothingTrend",
    "PolynomialTrendForecaster",
    # Core mathematics
    "difference_matrix",
    "difference_coefficients",
    "lambda_to_smoothness",
    "smoothness_to_lambda",
    "effective_degrees_of_freedom",
    "PurePenalizedSolver",
    "PureSolverResult",
    "pure_penalized_solution",
    "GuerreroSpectralSolver",
    "penalized_solution",
    "PureTrendDerivatives",
    "pure_trend_derivatives",
    "mse_from_prediction_derivatives",
    "roughness",
    # Forecasting
    "ForecastResult",
    "forecast_trend",
    "build_polynomial_from_tail",
    "ForecastAffineOperator",
    "finite_difference_forecast_operator",
    "ForecastLossDerivatives",
    "RollingForecastLossDerivatives",
    "PreparedRollingPureForecastObjective",
    "prepare_rolling_pure_forecast_objective",
    "pure_forecast_loss_derivatives",
    "rolling_pure_forecast_loss_derivatives",
    # Selection
    "TrainValidationSelector",
    "TimeWeightedValidationSelector",
    "golden_local",
    "find_all_local_minima",
    "LambdaOptimizationResult",
    "StationaryPoint",
    "StationaryPointSearchResult",
    "minimize_over_log_lambda",
    "newton_stationary_log_lambda",
    "find_stationary_points_log_lambda",
    "ForecastOptimalCandidate",
    "ForecastOptimalSelection",
    "select_fixed_window_pure_smoothness",
    "RecoveryLossDerivatives",
    "RecoveryOptimalSelection",
    "pure_recovery_loss_derivatives",
    "select_recovery_optimal_lambda",
    # Validation
    "mse_loss",
    "weighted_mse",
    "TimeWeightedValidationLoss",
    "make_time_weights",
    "train_val_test_split",
    "train_val_test_split_indices",
    "RollingOriginSplit",
    "rolling_origin_splits",
    "NestedForecastRecord",
    "NestedRollingForecastResult",
    "nested_rolling_pure_forecast",
    # Datasets
    "SyntheticTrendData",
    "make_polynomial_trend_series",
    "make_noisy_trend_series",
    "make_piecewise_trend_series",
    "make_sinusoidal_trend_series",
    "make_local_linear_trend_series",
    "make_structural_break_series",
    "make_local_linear_ar1_series",
    "make_two_regime_local_linear_series",
    # Metrics and benchmarks
    "mae",
    "mse",
    "rmse",
    "mape",
    "smape",
    "error_metrics_table",
    "compare_error_tables",
    "roughness_d",
    "BenchmarkResult",
    "BenchmarkRunner",
    "run_benchmark",
    "benchmark_metrics_table",
    "default_benchmark_models",
    "no_change_forecast",
    # Plotting
    "plot_smoothed_series",
    "plot_train_val_test_split",
    "plot_validation_curve",
    "plot_forecasted_trend",
    "plot_metrics_table",
    "plot_benchmark_forecasts",
    "plot_benchmark_metrics",
    "set_style",
]
