#!/usr/bin/env python3
"""Build a single Markdown bundle from literature/extracted/*.md."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT_DIR = REPO_ROOT / "literature" / "extracted"
DEFAULT_OUTPUT = REPO_ROOT / "literature" / "bundle.md"


def collect_markdown_files(
    extracted_dir: Path,
    output_path: Path,
) -> list[Path]:
    """Return all Markdown sources in deterministic order.

    The output file is excluded defensively in case a custom output path is
    placed inside the extracted directory.
    """
    output_resolved = output_path.resolve()
    files = [
        path
        for path in extracted_dir.rglob("*.md")
        if path.is_file() and path.resolve() != output_resolved
    ]
    return sorted(
        files,
        key=lambda path: path.relative_to(extracted_dir).as_posix().casefold(),
    )


def render_bundle(files: Iterable[Path], extracted_dir: Path) -> str:
    """Render source Markdown files into one AI-friendly bundle."""
    sources = list(files)

    lines: list[str] = [
        "# Literature Bundle",
        "",
        "> Auto-generated by `tools/build_literature_bundle.py`.",
        "> Source directory: `literature/extracted/`.",
        f"> Source files: **{len(sources)}**.",
        "> Do not edit this file by hand; regenerate it instead.",
        "",
        "## Contents",
        "",
    ]

    for index, path in enumerate(sources, start=1):
        relative = path.relative_to(extracted_dir).as_posix()
        lines.append(f"{index}. `{relative}`")

    lines.extend(["", "---", ""])

    for index, path in enumerate(sources, start=1):
        relative = path.relative_to(extracted_dir).as_posix()
        content = path.read_text(encoding="utf-8").rstrip()

        lines.extend(
            [
                f"<!-- BEGIN SOURCE {index}/{len(sources)}: {relative} -->",
                "",
                f"# Source: `{relative}`",
                "",
                content,
                "",
                f"<!-- END SOURCE {index}/{len(sources)}: {relative} -->",
                "",
                "---",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def build_bundle(
    extracted_dir: Path = DEFAULT_INPUT_DIR,
    output_path: Path = DEFAULT_OUTPUT,
) -> Path:
    """Build the bundle and return the written output path."""
    extracted_dir = extracted_dir.resolve()
    output_path = output_path.resolve()

    if not extracted_dir.is_dir():
        raise FileNotFoundError(f"Extracted directory not found: {extracted_dir}")

    files = collect_markdown_files(extracted_dir, output_path)
    if not files:
        raise RuntimeError(f"No Markdown files found under: {extracted_dir}")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_bundle(files, extracted_dir),
        encoding="utf-8",
        newline="\n",
    )
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bundle literature/extracted Markdown files into one file."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Directory containing extracted Markdown files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output bundle path.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output = build_bundle(args.input_dir, args.output)
    print(output)


if __name__ == "__main__":
    main()
